services:

  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    restart: no
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - net-pract-java
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
  backend:
    build: backend
    restart: no
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - net-pract-java
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 5173:5173 
    volumes:
      - ./frontend/src:/code/src
      - /project/node_modules
    networks:
      - net-pract-java
    depends_on:
      - backend

volumes:
  db-data: {}
networks:
  net-pract-java: {}